OPCIONS = -Wall -Wextra -Werror -Wno-sign-compare -std=c++11 -ansi

main.exe: main.o phone.o
	g++ -o main.exe main.o phone.o -lesin
	rm *.o

main.o: main.cpp llista.hpp phone.rep
	g++ -c main.cpp $(OPCIONS)

phone.o: phone.cpp phone.hpp phone.rep
	g++ -c phone.cpp $(OPCIONS)

clean:
	rm *.o
	rm *.exe
	rm *.gch